version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: swiftly/php:7.3
    volumes:
     - .:/var/www/html
    networks:
     - net
  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "secret"
    cap_add:
      - SYS_NICE
    volumes:
      - ./data/sql/development.sql:/docker-entrypoint-initdb.d/development.sql
    networks:
      - net
networks:
  net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
